[".zsh/zsh-plugins/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".zsh/zsh-plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".zsh/zsh-plugins/zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".zsh/zsh-plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
