- name: Dotfile automation
  gather_facts: true
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - ./brew_packages.yml
    - ./dotfiles_path.yml
  tasks:

    - name: Check if community.general collection is installed
      ansible.builtin.command: ansible-galaxy collection list
      register: collection_list

    - name: Install community.general collection if not present
      ansible.builtin.shell: "ansible-galaxy collection install community.general ansible.posix"
      when: "'community.general' not in collection_list.stdout"
    
    - name: Upgrade the rpm-ostree image
      ansible.posix.rpm_ostree_upgrade:

    - name: Install brew packages
      community.general.homebrew:
        name: "{{ brew_packages }}"
        state: present
        update_homebrew: true
        upgrade_all: true
    
    # - name: Update distrobox containers
    #   ansible.builtin.shell: "distrobox-upgrade --all"

    - name: Create symlinks
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest | expanduser }}"
        state: link
      loop: "{{ links }}"