# allow mouse selection
set -g default-terminal "xterm-256color"
set -g mouse on
set -s escape-time 0
set -g repeat-time 1000
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
unbind C-b
unbind '"'
unbind %
set -g prefix C-Space
bind Space send-prefix

set -g @plugin 'tmux-plugins/tmux-yank'
bind -T copy-mode    C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
bind -T copy-mode-vi C-c send -X copy-pipe-no-clear "xsel -i --clipboard"

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

run '/home/linuxbrew/.linuxbrew/opt/tpm/share/tpm/tpm'
