add_newline = false
format = "$username$hostname$git_branch$git_commit$git_state$git_status$directory \n $character"
command_timeout = 900

[character]
error_symbol = "[\\$](bright-red bold)"
success_symbol = "[>_](bright-green bold)"

[directory]
read_only = " 󰉐"
truncation_length = 0
format = '[$path]($style)'

[git_branch]
format = "[$symbol$branch]($style) "
only_attached = true
style = "bright-yellow bold"
symbol = " "

[git_commit]
format = "[$hash]($style) "
only_detached = true
style = "bright-yellow bold"

[git_state]
style = "bright-purple bold"

[git_status]
style = "bright-green bold"

[hostname]
format = "[$ssh_symbol$hostname ]($style)"
ssh_only = false
style = "bright-blue bold"

[nodejs]
format = "via [󰎙 $version](bold green) "

[username]
format = "[$user@]($style)"
disabled = false
show_always = true
style_root = "bright-red bold"
style_user = "pink bold"
